modelNamePrefix: ""
packageVersion: "1.1.4"
modelNameSuffix: ""
apiNameSuffix: "Api"
repositoryUrl: "https://github.com/GovCraft/mistral-rouille"
bestFitInt: true
modelPropertyNaming: "camelCase"
hideGenerationTimestamp: false
packageName: "mistral-rouille"
projectName: "MistralRouille"
library: "reqwest"
supportAsync: true
preferUnsignedInt: true
supportMultipleResponses: true
useSingleRequestParameter: true
infoEmail: roland@govcraft.ai
typeMappings:
  int: isize
  integer: isize
  str: String
avoidBoxedModels: true
